services:
  easyMoney:
    image: calrock/easymoney:latest
    container_name: easyMoney
    restart: always
    ports:
      - "3186:3186"
    volumes:
      - easyMoney:/app/data
    #    You can use a bind mount instead of a volume if you prefer      
    #      - path/to/your/easyMoney-data:/app/data
    environment:
      - DATABASE_URL=file:/app/data/easyMoney.db
      - LOG_LEVEL=INFO
      - PORT=3186
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/.next/cache
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:$${PORT}" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
